insert into pais values ('use viajes
create table pais('
Id pais int,
pais varchar ('255'),
capital varchar ('255'),
continente varchar ('255')


insert into pais values (1,'Afganistán','Kabul','Asia')
insert into pais values (2'Albania','Tirana','Europa')
insert into pais values (3,'Alemania','Berlín','Europa')
insert into pais values (4,'Andorra','Andorra la Vieja','Europa')
insert into pais values (5,'Angola','Luanda','África')
insert into pais values (6,'Antigua y Barbuda','Saint John	','América')
insert into pais values (7,'Arabia Saudita','Riad','Asia')
insert into pais values (8,'Argelia	Argel','África')
insert into pais values (9,'Argentina','Buenos Aires','América')
insert into pais values (10,'Armenia','Ereván','Asia')
insert into pais values (11,'Australia','Canberra','Oceanía')
insert into pais values (12,'Austria','Viena','Europa')
insert into pais values (13,'Azerbaiyán','Bakú','Asia')
insert into pais values (14,'Bahamas','Nasáu','América')
insert into pais values (15,'Bangladés','Daca','Asia')
insert into pais values (16,'Barbados','Bridgetown','América')
insert into pais values (17,'Baréin','Manama','Asia')
insert into pais values (18,'Bélgica','Bruselas','Europa')
insert into pais values (19,'Belice','Belmopán','América')
insert into pais values (20,'Benín','Porto-Novo','África')
insert into pais values (21,'Bielorrusia','Minsk','Europa')
insert into pais values (22,'Birmania','Naipyidó','Asia')
insert into pais values (23,'Bolivia','Sucre','América')
insert into pais values (24,'Bosnia-Herzegovina','Sarajevo	','Europa')
insert into pais values (25,'Botsuana','Gaborone','África')
insert into pais values (26,'Brasil','Brasilia','América')
insert into pais values (27,'Brunéi	Bandar','Seri Begawan','Asia')
insert into pais values (28,'Bulgaria','Sofía','Europa')
insert into pais values (29,'Burkina Faso','Uagadugú','África')
insert into pais values (30,'Burundi','Buyumbura','África')
insert into pais values (31,'Bután','Thimphu','Asia')
insert into pais values (32,'Cabo Verde','Praia','África')
insert into pais values (33,'Camboya','Nom Pen','Asia')
insert into pais values (34,'Camerún','Yaundé','África')
insert into pais values (35,'Canadá','Ottawa','América')
insert into pais values (36,'Catar','Doha','Asia')
insert into pais values (37,'Chad','Yamena','África')
insert into pais values (38,'Chile','Santiago','América')
insert into pais values (39,'China','Pekín','Asia')
insert into pais values (40,'Chipre','Nicosia','Europa')
insert into pais values (41,'Colombia','Bogotá','América')
insert into pais values (42,'Comoras','Moroni','África')
insert into pais values (43,'Congo','Brazzaville','África')
insert into pais values (44,'Corea del Norte','Pionyang','Asia')
insert into pais values (45,'Corea del Sur','Seúl','Asia')
insert into pais values (46,'Costa de Marfil','Yamusukro','África')
insert into pais values (47,'Costa Rica','San José','América')
insert into pais values (48,'Croacia','Zagreb','Europa')
insert into pais values (49,'Cuba','La Habana','América')
insert into pais values (50,'Dinamarca','Copenhague','Europa')
insert into pais values (,Dominica','Roseau	','América')
insert into pais values (,Ecuador','Quito','América')
insert into pais values (,Egipto','El Cairo	','África')
insert into pais values (,El Salvador','San Salvador	','América')
insert into pais values (,Emiratos Árabes Unidos','Abu Dabi	','Asia')
insert into pais values (,Eritrea','Asmara	','África')
insert into pais values (,Eslovaquia','Bratislava	','Europa')
insert into pais values (,Eslovenia','Liubliana	','Europa')
insert into pais values (,España','Madrid	','Europa')
insert into pais values (,Estados Unidos','Washington D. C.	','América')
insert into pais values (,Estonia','Tallin	','Europa')
insert into pais values (,Etiopía	Adís Abeba	','África')
insert into pais values (,Filipinas	Manila	','Asia')
insert into pais values (,Finlandia	Helsinki	','Europa')
insert into pais values (,Fiyi	Suva	','Oceanía')
insert into pais values (,Francia	París	','Europa')
insert into pais values (,Gabón	Libreville	','África')
insert into pais values (,Gambia	Banjul	','África')
insert into pais values (,Georgia	Tiflis	','Asia')
insert into pais values (,Ghana	Accra	','África')
insert into pais values (,Granada	Saint George	','América')
insert into pais values (,Grecia	Atenas	','Europa')
insert into pais values (,Guatemala	Guatemala	','América')
insert into pais values (,Guinea	Conakri	','África')
insert into pais values (,Guinea Ecuatorial	Malabo	','África')
insert into pais values (,Guinea-Bisáu	Bisáu	','África')
insert into pais values (,Guyana	Georgetown	','América')
insert into pais values (,Haití	Puerto Príncipe	','América')
insert into pais values (,Honduras	Tegucigalpa	','América')
insert into pais values (,Hungría	Budapest	','Europa')
insert into pais values (,India	Nueva Delhi	','Asia')
insert into pais values (,Indonesia	Yakarta	','Asia')
insert into pais values (,Irak	Bagdad	','Asia')
insert into pais values (,Irán	Teherán	','Asia')
insert into pais values (,Irlanda	Dublín	','Europa')
insert into pais values (,Islandia	Reikiavik	','Europa')
insert into pais values (,Islas Marshall	Majuro	','Oceanía')
insert into pais values (,Islas Salomón	Honiara	','Oceanía')
insert into pais values (,Israel	Jerusalén	','Asia')
insert into pais values (,Italia	Roma	','Europa')
insert into pais values (,Jamaica	Kingston	','América')
insert into pais values (,Japón	Tokio	','Asia')
insert into pais values (,Jordania'	'Amán'	''.'Asia',')
insert into pais values (,Kazajistán	Astaná	','Asia')
insert into pais values (,Kenia	Nairobi	','África')
insert into pais values ('Kirguistán	Biskek	','Asia')
insert into pais values ('Kiribati	Tarawa	','Oceanía')
insert into pais values ('Kosovo	Pristina	','Europa')
insert into pais values ('Kuwait	Kuwait City	','Asia')
insert into pais values ('Laos	Vientián	','Asia')
insert into pais values ('Lesoto	Maseru	','África')
insert into pais values ('Letonia	Riga	','Europa')
insert into pais values ('Líbano	Beirut	','Asia')
insert into pais values ('Liberia	Monrovia	','África')
insert into pais values ('Libia	Trípoli	','África')
insert into pais values ('Liechtenstein	Vaduz	','Europa')
insert into pais values ('Lituania	Vilna	','Europa')
insert into pais values ('Luxemburgo	Luxemburgo	','Europa')
insert into pais values ('Macedonia	Skopie	','Europa')
insert into pais values ('Madagascar	Antananarivo	','África')
insert into pais values ('Mal'.'Asia	Kuala Lumpur	','Asia')
insert into pais values ('Malaui	Lilongüe	','África')
insert into pais values ('Maldivas	Malé	','Asia')
insert into pais values ('Malí	Bamako	','África')
insert into pais values ('Malta	La Valeta	','Europa')
insert into pais values ('Marruecos	Rabat	','África')
insert into pais values ('Mauricio	Port Louis	','África')
insert into pais values ('Mauritania	Nuakchot	','África')
insert into pais values ('México	México	','América')
insert into pais values (,Micronesia	Palikir	','Oceanía')
insert into personas values (,Moldavia	Chisináu	','Europa')
insert into personas values (,Mónaco	Mónaco	','Europa')
insert into personas values (,Mongolia	Ulán Bator	','Asia')
insert into personas values (,Montenegro	Podgorica	','Europa')
insert into personas values (,Mozambique	Maputo	','África')
insert into personas values (,Namibia	Windhoek	','África')
insert into personas values (,Nauru	Yaren	','Oceanía')
insert into personas values (,Nepal	Katmandú	','Asia')
insert into personas values (,Nicaragua	Managua	','América')
insert into personas values (,Níger	Niamey	','África')
insert into personas values (,Nigeria	Abuya	','África')
insert into personas values (,Noruega	Oslo	','Europa')
insert into personas values (,Nueva Zelanda	Wellington	','Oceanía')
insert into personas values (,Omán	Mascate	','Asia')
insert into personas values (,Países Bajos	Ámsterdam	'.'Europa')
insert into personas values (,Pakistán	Islamabad	','Asia')
insert into personas values (,Palaos	Melekeok	','Oceanía')
insert into personas values (,Palestina	Jerusalén Este	','Asia')
insert into personas values (,Panamá	Panamá	','América')
insert into personas values (,Papúa Nueva Guinea	Puerto Moresby	','Oceanía')
insert into personas values (,Paraguay	Asunción	','América')
insert into personas values (,Perú	Lima	','América')
insert into personas values (,Polonia	Varsovia	','Europa')
insert into personas values (,Portugal	Lisboa	','Europa')
insert into personas values (,Reino Unido	Londres	','Europa')
insert into personas values (,República Centroafricana	Bangui	','África')
insert into personas values (,República Checa	Praga	','Europa')
insert into personas values (,República Democrática del Congo	Kinsasa	','África')
insert into personas values (,República Dominicana	Santo Domingo	','América')
insert into personas values (,Ruanda	Kigali	','África')
insert into personas values (,Samoa	Apia	','Oceanía')
insert into personas values (,San Cristóbal y Nieves	Basseterre	','América')
insert into personas values (,San Marino	San Marino	','Europa')
insert into personas values (,San Vicente y las Granadinas	Kingstown	','América')
insert into personas values (,Santa Lucía	Castries	','América')
insert into personas values (,Santo Tomé y Príncipe	Santo Tomé	','África')
insert into personas values (,Senegal	Dakar	','África')
insert into personas values (,Serbia	Belgrado	','Europa')
insert into personas values (,Seychelles	Victoria	','África')
insert into personas values (,Sierra Leona	Freetown	','África')
insert into personas values (,Singapur	Singapur	','Asia')
insert into personas values (,Siria	Damasco	','Asia')
insert into personas values (,Somalia	Mogadiscio	','África')
insert into personas values (,Sri Lanka	Sri Jayawardenapura Kotte	','Asia')
insert into personas values (,Suazilandia	Mbabane	','África')
insert into personas values (,Sudáfrica	Pretoria	','África')
insert into personas values (,Sudán	Jartum	','África')
insert into personas values (,Sudán del Sur	Yuba	','África')
insert into personas values (,Suecia	Estocolmo	','Europa')
insert into personas values (,Suiza	Berna	','Europa')
insert into personas values (,Surinam	Paramaribo	','América')
insert into personas values (,Tailandia	Bangkok	','Asia')
insert into personas values (,Taiwán	Taipéi	','Asia')
insert into personas values (,Tanzania	Dodoma	','África')
insert into personas values (,Tayikistán	Dusambé	','Asia')
insert into personas values (,Timor Oriental	Dili	','Oceanía')
insert into personas values (,Togo	Lomé	','África')
insert into personas values (,Tonga	Nukualofa	','Oceanía')
insert into personas values (,Trinidad y Tobago	Puerto España	','América')
insert into personas values (,Túnez	Túnez	','África')
insert into personas values (,Turkmenistán	Asjabad	','Asia')
insert into personas values (,Turquía	Ankara	','Asia')
insert into personas values (,Tuvalu	Funafuti	','Oceanía')
insert into personas values (,Ucrania	Kiev	','Europa')
insert into personas values (,Uganda	Kampala	','África')
insert into personas values (,Uruguay	Montevideo	','América')
insert into personas values (,Uzbekistán	Taskent	','Asia')
insert into personas values (,Vanuatu	Port Vila	','Oceanía')
insert into pais values ('Vaticano	Vaticano	','Europa')
insert into pais values ('Venezuela	Caracas	','América')
insert into pais values ('Vietnam	Hanói	','Asia')
insert into pais values ('Yemen	Saná	','Asia')
insert into pais values ('Yibuti	Yibuti	','África')
insert into pais values ('Zambia	Lusaka	','África')
insert into pais values ('Zimbabue	Harare	','África')

